vim9script

# disable default plugins
const g:netrw_silent: bool = 1
const g:loaded_rrhelper: bool = 1
const g:loaded_gzip: bool = 1
const g:loaded_getscriptPlugin: bool = 1
const g:loaded_vimballPlugin: bool = 1
const g:loaded_netrwPlugin: bool = 1
const g:loaded_zipPlugin: bool = 1
const g:loaded_manpager: bool = 1
const g:loaded_spellfile: bool = 1
const g:loaded_tohtml: bool = 1
# let g:loaded_fzf = 1
const g:loaded_matchparen: bool = 1
const g:loaded_logiPat: bool = 1
const g:loaded_tarPlugin: bool = 1
const g:netrw_use_noswf: bool = 0


# encoding
set encoding=utf-8
set fileencoding=utf-8

# theme and font
syntax on
colorscheme codedark
set ttyfast
set nolazyredraw
set guifont=Sauce\ Code\ Pro\ Nerd\ Font\ 14
set guioptions=c

# nocompatible for disable deprecated futures
set nocompatible

# search
set iminsert=0
set imsearch=0
set hlsearch

# numbers and relativenumbers
set number
set relativenumber

# cursor
set cursorline

# dont show current mode
set noshowmode

# active status lines (for lightline)
set laststatus=2
set showtabline=2

# indent
set shiftwidth=2
set tabstop=2
set smarttab
set smartindent
set autoindent
set expandtab

# allow cursor to move where there is no text in visual block mode
# set virtualedit=block
# now disabled

# filetypes plugins
filetype plugin on
filetype indent on

# auto read file
set autoread
set updatetime=200

# wild menu for autocomplete command on command mode
set wildmenu
set wildoptions=pum
set pumheight=10

# enable mouse mode in all modes
set mouse=a

# enable clipboard support
set clipboard=unnamedplus

# correct splits
set splitbelow
set splitright

# enable autocomplete on tab
set omnifunc=ale#completion#OmniFunc
set completeopt=menu,preview
set completepopup=height:10,width:60
const g:SuperTabDefaultCompletionType: string = "<C-n>"

# options for ALE
highlight ALEErrorSign ctermbg =NONE ctermfg=red
highlight ALEWarningSign ctermbg =NONE ctermfg=yellow

g:ale_linters = {
  "nim": ["nimlsp", "nimcheck"]
}

g:ale_fixers = {
  "*": ["remove_trailing_lines", "trim_whitespace"],
  "nim": ["nimpretty"]
}

# set lightline colorscheme
const g:lightline = {'colorscheme': 'codedark'}

# remove trailing whitespaces on save
autocmd BufWritePre * :%s/\s\+$//e


# keys
set winaltkeys=yes
# tabs keys
nnoremap <C-b> :tabnew<CR>
nnoremap <C-c> :tabclose<CR>
nnoremap <C-n> :tabnext<CR>
nnoremap <C-p> :tabprevious<CR>

# splits keys
nnoremap <C-k> :vsplit<CR>
nnoremap <C-l> :split<CR>

# save and exit keys
nnoremap <C-q> :q<CR>
nnoremap <C-s> :w<CR>

# spawn floating terminal
nnoremap <C-z> :FloatermNew<CR>

# spawn fern.vim file manager
nnoremap <C-t> :Fern . -drawer -width=27 -wait<CR>

